### ISSUE TITLE
add to opam?

### ISSUE THREAD

**Issue by struktured** [hcarty/ocaml-plplot#1]
Any plans to add an opam file and possibly release it to the opam repo?

**Comment by hcarty** [comment]
Completed with the merge of #2, thank you again!

**Comment by struktured** [comment]
so let's release this thing! I plan on releasing stuff which depends on it soonish. I can update the README.md if you like. Assuming that's all we really need, if you tag the thing I can also PR it on the opam-repository for you.

**Comment by hcarty** [comment]
@struktured Any help/contributions you can offer here and in updating opam-repository would be very welcome!  Thank you for your help.

**Comment by hcarty** [comment]
Absurdly long overdue... https://github.com/ocaml/opam-repository/pull/6797

I'll close this once the opam-repository PR is merged.  Sorry this has taken so long!

**Comment by struktured** [comment]
Oops forgot about this. Thanks!

**Comment by hcarty** [comment]
The PR was merged - ocaml-plplot should now be accessible through `opam install plplot`!

**Comment by struktured** [comment]
:+1:
