### ISSUE TITLE
Ocaml 5.0.0

### ISSUE THREAD

**Issue by priamfive** [hcarty/ocaml-plplot#7]
I think pull request #5 made this package compatible with Ocaml 5.0.0 but Opam complains
that it requires Ocaml < 5.0.0 when I try to install it. Perhaps the new version needs to be pushed to the opam directory (or however this works - not an expert).

**Comment by mseri** [comment]
You are right, the package is not released in opam. I'll submit a release asap

**Comment by mseri** [comment]
PR for release https://github.com/ocaml/opam-repository/pull/22924
